version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - rag_network
  pgadmin:
    image: dpage/pgadmin4:8          # latest pgAdmin 4
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"                   # browser → http://localhost:5050
    depends_on:
      - db
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
